### ISSUE TITLE
unsupported operand type

### ISSUE THREAD

**Issue by maddrid** [Alex-Lekov/trade-data-collection-service#5]
Traceback (most recent call last):
candles-data_quality_check-1  |   File "/app/./data_quality_check.py", line 212, in <module>
candles-data_quality_check-1  |     main()
candles-data_quality_check-1  |   File "/app/./data_quality_check.py", line 198, in main
candles-data_quality_check-1  |     check_last_data_recording(ch)
candles-data_quality_check-1  |   File "/app/./data_quality_check.py", line 94, in check_last_data_recording
candles-data_quality_check-1  |     time_diff = datetime.datetime.now() - df.stop.min()
candles-data_quality_check-1  | TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'float'

**Comment by Alex-Lekov** [comment]
fix it
